name: Bump Gem / Create PR
on:
  push:
  workflow_dispatch:
    inputs:
      new-gem-version:
        type: choice
        options:
          - major
          - minor
          - patch
          - pre
          - release
        required: true

jobs:
  release:
    name: Bump Gem / Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: |
          bundle exec gem bump --version ${{ github.event.inputs.new-gem-version || 'patch' }} --no-commit
          NEW_VERSION=$(ruby -r ./lib/serverless-tools/version.rb -e "puts ServerlessTools::VERSION")
          bundle config unset deployment
          bundle install
          ruby -pi.bak -e "gsub(/serverless-tools-gha\:.*\"/, 'serverless-tools-gha:v$NEW_VERSION\"')" action.yml
                
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Gem bump $NEW_VERSION - ${{ github.actor }}
          branch: ${{ github.event.inputs.new-gem-version || 'patch' }}-${{ github.actor }}
          create_branch: true
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Gem bump $NEW_VERSION - ${{ github.actor }}" --fill

