name: Bump Gem / Create PR
on:
  push:
  workflow_dispatch:
    inputs:
      new-gem-version:
        type: choice
        options:
          - major
          - minor
          - patch
          - pre
          - release
        required: true

jobs:
  release:
    name: Bump Gem / Create PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - run: |
          NEW_GEM_VERSION_OPTION=${{ github.event.inputs.new-gem-version || 'patch' }}
          git checkout -b $NEW_GEM_VERSION_OPTION-${{ github.actor }}-$(date +'%d-%m')
          bundle exec gem bump --version $NEW_GEM_VERSION_OPTION
          NEW_VERSION=$(ruby -e "require_relative './lib/serverless-tools/version.rb'; puts ServerlessTools::VERSION")
          bundle install
          ruby -pi.bak -e "gsub(/serverless-tools-gha\:.*\"/, 'serverless-tools-gha:v$NEW_VERSION\"')" action.yml
          git add Gemfile.lock action.yml
          git commit --amend -CHEAD
          # git push git@github.com:fac/serverless-tools.git
          gh pr create --title "Gem bump $NEW_VERSION" --body "Gem bump"
