name: Create Gem Bump Branch
on:
  workflow_dispatch:
    inputs:
      version-bump-significance:
        type: choice
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - pre
          - release
        required: true

jobs:
  release:
    name: Bump Gem / Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Perform gem bump
        run: |
          bundle exec gem bump \
            --version ${{ github.event.inputs.version-bump-significance }} \
            --no-commit

      - name: Update action.yml with new version
        run: |
          NEW_VERSION=$(ruby \
            -r ./lib/serverless-tools/version.rb \
            -e "puts ServerlessTools::VERSION"\
          )

          ruby -pi \
          -e "gsub( \
            /serverless-tools-gha\:.*\"/, \
            'serverless-tools-gha:v$NEW_VERSION\"' \
          )" action.yml

      - name: Bundle install with new version
        run: |
          bundle config unset deployment
          bundle install

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.inputs.version-bump-significance }} gem bump - ${{ github.actor }}
          file_pattern: 'action.yml Gemfile.lock lib/serverless-tools/version.rb'
          branch: ${{ github.event.inputs.version-bump-significance }}-${{ github.actor }}
          create_branch: true
          push_options: '--force'

      - name: Post link to create a pull request from newly pushed branch
        run: |
          GITHUB_NEW_PR_URL="https://github.com/fac/serverless-tools/compare/${{ github.event.inputs.version-bump-significance }}-${{ github.actor }}?expand=1"
          echo "::notice::Create a PR here: ${GITHUB_NEW_PR_URL}"
