name: Slack Messages

on:
  workflow_call:
    outputs:
      start-message:
        description: Slack message for the start of deployment
        value: ":building_construction: *DEPLOYING* ${{ jobs.build-message.outputs.deploy-details }}"
      success-end-message:
        description: Slack message for a successful end of deployment
        value: ":tada: *DEPLOYED* ${{ jobs.build-message.outputs.deploy-details }}"
      failure-end-message:
        description: Slack message for a failed or cancelled deployment
        value: ":x: *FAILED* ${{ jobs.build-message.outputs.deploy-details }}"
jobs:
  build-message:
    runs-on: ubuntu-latest
    outputs:
      deploy-details: ${{ steps.format-deployment-details.outputs.deploy_details }}
    steps:
      - name: Format deployment details
        id: format-deployment-details
        env:
          GITHUB_AUTHOR: ${{ github.event.head_commit.author.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number="$( gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls --jq '.[0].number' )"
          commit_msg="$( gh api repos/${{ github.repository }}/commits/${{ github.sha }} -q .commit.message | head -1 )"
          short_commit_id="$( echo "${{ github.sha }}" | cut -c-11 )"
          slack_name="$( echo "$GITHUB_AUTHOR" | tr '[:upper:]' '[:lower:]' | tr ' ' . | tr -d "'")"
          repo_url="${{ github.server_url }}/${{ github.repository }}"
          workflow_run_url="${repo_url}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"
          mrkdwn_commit=":github: <${repo_url}/commit/${{github.sha}}|${short_commit_id}> ${commit_msg}"
          mrkdwn_run="<${workflow_run_url}|${{github.repository}}/${{github.ref_name}} #${{ github.run_number }}> for @${slack_name}"
          mrkdwn_pr="<${repo_url}/pull/${pr_number}|#${pr_number}>"
          mrkdwn_deploy_details="${mrkdwn_run}\n${mrkdwn_commit} (${mrkdwn_pr})"

          echo "deploy_details=$mrkdwn_deploy_details" >> "$GITHUB_OUTPUT"
